id: I53B0B57B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T23:12:39+00:00'
last_modified: '2022-06-07T12:42:00.856591+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3413
  title: བརྡ་སྤྲོད་དཔེ་རྙིང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    68BB:
      image_group_id: I3CN4488
      title: ''
      total_pages: 480
      order: 1
      base_file: 68BB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
