id: P000702
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-16 16:37:53.598851
source_metadata:
  id: bdr:W3CN3413
  title: བརྡ་སྤྲོད་དཔེ་རྙིང་།
  author: ''
  volumes:
    ac7b804275de4685806d218a359cec42:
      image_group_id: I3CN4488
      title: ''
      volume_number: 1
      total_pages: 480
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
